local lpeg = require "lpeg"

describe("URI", function()
	local uri = require "lpeg_patterns.uri".uri * lpeg.P(-1)
	it("Should match file urls", function()
		assert.same({scheme = "file", path = "/var/log/messages"}, uri:match "file:///var/log/messages")
		assert.same({scheme = "file", path = "/C:/Windows/"}, uri:match "file:///C:/Windows/")
	end)
	it("Should match localhost", function()
		assert.same({host="localhost"}, uri:match "localhost")
		assert.same({host="localhost", port=8000}, uri:match "localhost:8000")
		assert.same({scheme = "http", host="localhost", port=8000}, uri:match "http://localhost:8000")
	end)
	it("Should work with IPv6", function()
		assert.same({host="0:0:0:0:0:0:0:1"}, uri:match "[::1]")
		assert.same({host="0:0:0:0:0:0:0:1", port=80}, uri:match "[::1]:80")
	end)
	it("IPvFuture", function()
		assert.same({host="v4.2", port=80}, uri:match "[v4.2]:80")
	end)
	it("Should work with IPv6 zone local addresses", function()
		assert.same({host="0:0:0:0:0:0:0:1%eth0"}, uri:match "[::1%25eth0]")
	end)
end)

describe("Sane URI", function()
	local sane_uri = require "lpeg_patterns.uri".sane_uri
	it("Not match the empty string", function()
		assert.falsy ( sane_uri:match "" )
	end)
	it("Not match misc words", function()
		assert.falsy ( sane_uri:match "the quick fox jumped over the lazy dog." )
	end)
	it("Not match numbers", function()
		assert.falsy( sane_uri:match "123" )
		assert.falsy( sane_uri:match "17.3" )
		assert.falsy( sane_uri:match "17.3234" )
		assert.falsy( sane_uri:match "17.3234" )
	end)
end)
